name: vulnerability scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.7
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
                MGA_GITHUB_USER: ${{ secrets.MY_GITHUB_USERNAME }}
                MGA_GITHUB_TOKEN: ${{ secrets.MGA_GITHUB_TOKEN }}
                GOPRIVATE: "github.com/MeterianHQ"
            with:
                cli_args: "" #[ Meterian CLI Options ]
