name: vulnerability scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.5
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
                MGA_GITHUB_USER: "n-insaidoo"
                MGA_GITHUB_TOKEN: ${{ secrets.MGA_GITHUB_TOKEN }}
                MGA_BITBUCKET_USER: "n-insaidoo"
                MGA_BITBUCKET_APP_PASSWORD: ${{ secrets.MGA_BITBUCKET_APP_PASSWORD }}
                MGA_GITLAB_USER: "n-insaidoo"
                MGA_GITLAB_TOKEN: ${{ secrets.MGA_GITLAB_TOKEN }}
                GOPRIVATE: "github.com/n-insaidoo,bitbucker.org/n-insaidoo,gitlab.com/n-insaidoo"
            with:
                cli_args: "--debug" #[ Meterian CLI Options ]
