name: vulnerability scan workflow

on: push

jobs:
    meterian_scan:
        name: Meterian client scan
        runs-on: ubuntu-latest
        steps: 
          - name: Checkout
            uses: actions/checkout@v2
          - name: Scan project with the Meterian client
            uses: MeterianHQ/meterian-github-action@v1.0.4-canary
            env:
                METERIAN_API_TOKEN: ${{ secrets.METERIAN_API_TOKEN }}
                MGA_GITHUB_USER: "n-insaidoo"
                MGA_GITHUB_TOKEN: "e55f9821846350d7ff5bf52b7f255c5e416efffc"
            with:
                cli_args: "" #[ Meterian CLI Options ]
